// Code generated by go tool dist; DO NOT EDIT.

package objabi

import "runtime"

const defaultGO386 = `sse2`
const defaultGOARM = `7`
const defaultGOMIPS = `hardfloat`
const defaultGOOS = runtime.GOOS
const defaultGOARCH = runtime.GOARCH
const defaultGO_EXTLINK_ENABLED = ``
const stackGuardMultiplier = 1
const goexperiment = ``

var version = "1.0" // runtime.Version()
